gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#5c7aab"
    # cherryPickedCommitFgColor:
    #   - "#89b4fa"
    # cherryPickedCommitBgColor:
    #   - "#45475a"
    # markedBaseCommitFgColor:
    #   - "#89b4fa"
    # markedBaseCommitBgColor:
    #   - "#f9e2af"
    # unstagedChangesColor:
    #   - "#f38ba8"
    # defaultFgColor:
    #   - "#cdd6f4"
    # searchingActiveBorderColor:
    #   - "#f9e2af"
  # authorColorDefault: "#b4befe"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
