return {
  -- {
  --   "nvimtools/none-ls.nvim",
  --   config = function()
  --     vim.keymap.set("n", "<leader>gf", vim.lsp.buf.format, { silent = true })
  --   end,
  -- },
  -- {
  --   "jay-babu/mason-null-ls.nvim",
  --   event = { "BufReadPre", "BufNewFile" },
  --   dependencies = {
  --     "williamboman/mason.nvim",
  --     "nvimtools/none-ls.nvim",
  --   },
  --   config = function()
  --     require("mason").setup()
  --     require("mason-null-ls").setup({
  --       ensure_installed = { "stylua" },
  --       automatic_installation = true,
  --     })
  --
  --     local null_ls = require("null-ls")
  --     null_ls.setup({
  --       sources = {
  --         null_ls.builtins.formatting.prettier.with({
  --           filetypes = { "javascript", "typescript" },
  --         }),
  --       },
  --     })
  --   end,
  -- },
}
